import ContextApi from "./CustomContext";


function Home(){
  
    return <>
     <h1>Home component</h1>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis consequuntur repellat doloremque corrupti, laudantium minus ratione, id labore vero, aliquid repudiandae iste reiciendis obcaecati cumque ex illum voluptatem quo nostrum omnis repellendus magnam quae ipsam rerum! Beatae dolore, unde ratione qui dolor incidunt sapiente molestiae explicabo atque architecto possimus pariatur omnis modi in earum perferendis! Doloribus eum molestiae esse debitis, excepturi enim, rerum atque a non quod repellendus nisi consectetur aliquam! Tenetur, sunt. Odit a molestias aspernatur eius suscipit repudiandae laborum similique dicta, ipsum nemo. Qui eos ipsa neque culpa veritatis rerum! Eaque veniam ipsum ratione sapiente assumenda fuga labore, ex minus dolores provident numquam, id, dolore saepe suscipit consequuntur pariatur repellat fugiat. Qui repellendus aut aliquam. Enim commodi minima sint nostrum earum ex a quibusdam vel, pariatur veritatis totam, iusto id saepe beatae necessitatibus impedit doloremque, ipsa fuga asperiores hic facilis qui tempora sed! Unde, ullam aperiam pariatur fugit, officiis vitae animi laborum praesentium, corporis nihil error. Eaque, dolorum ratione quam impedit maxime dolor! Officiis aliquid sapiente tenetur ea dignissimos voluptatum voluptatibus vero temporibus nemo asperiores libero, consequuntur saepe quidem dolorum tempore earum veritatis magnam! Veritatis fuga odio fugiat nesciunt beatae deleniti unde explicabo ad blanditiis, assumenda laboriosam impedit expedita deserunt non, iste temporibus! Debitis vel placeat quidem, quia labore quam saepe dolores est sint a reiciendis quaerat iusto. Dolores quis ipsam sapiente mollitia? Quis, harum officia repudiandae nostrum deserunt doloremque officiis dolor ea iure enim accusamus modi ex alias optio quos sit. Sapiente illo voluptatum, molestiae earum nostrum, error suscipit ex repellendus veniam unde consequatur quis labore quidem sed? Nobis officia voluptate obcaecati commodi beatae, mollitia, libero quod natus dolore ex voluptates, et sit minima eveniet dolores ducimus. Iste error, dolores et ex quidem soluta numquam quam earum cumque officiis quisquam laboriosam temporibus officia repellat veniam nam quis.</p>
     <br/>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam consequuntur cumque dolorem qui accusantium ex labore fugiat ut iusto. Dignissimos illum dolorem accusantium possimus exercitationem nulla et sunt, id est fugiat facere magnam dolorum illo deleniti molestiae quae porro nostrum modi hic eligendi asperiores, rem unde. Iure, assumenda. Maxime quia, labore repellat excepturi quis sit aliquid quas, hic corrupti omnis corporis unde quo nostrum natus! Dignissimos, inventore reprehenderit adipisci voluptatem sunt, quaerat animi nesciunt fugiat repellendus iusto provident quas perspiciatis, vel laudantium vitae explicabo? Adipisci natus dignissimos, doloremque architecto eveniet alias rerum distinctio reprehenderit saepe perferendis maxime iste beatae fugit animi tenetur numquam soluta quas voluptate optio. Error quas modi quidem. Vero, deleniti, distinctio provident mollitia officia adipisci nostrum aliquam, consequuntur quas error quod modi fuga minima nobis soluta nihil numquam. Molestias modi ea inventore aliquam, exercitationem libero in saepe placeat accusamus sed facilis, ab quae vel reprehenderit dolore corrupti? Totam provident ullam ex, perferendis iste inventore ducimus architecto eveniet cumque temporibus sed ipsa corporis pariatur id placeat, porro fugit ratione, commodi esse quisquam fuga exercitationem nostrum. Ipsum dolore assumenda impedit ex voluptate obcaecati ab exercitationem iste iusto delectus commodi, officiis perspiciatis eos officia quasi tempore eligendi! Accusamus voluptate quaerat quis magnam expedita cum laborum. Maiores excepturi facere repellat assumenda. Iste aut voluptatum explicabo distinctio quisquam perspiciatis ducimus ipsam quia possimus deserunt autem enim, nemo dignissimos dolores nesciunt asperiores amet cupiditate. Ratione, praesentium a maxime ipsum repudiandae quia, officia consequatur quo explicabo totam harum placeat sunt? Eveniet, quo? Veritatis quae quis ratione rerum at iusto harum aliquam sed itaque quia excepturi esse, eveniet veniam? Amet consectetur quae recusandae doloribus adipisci, dolorem eaque corporis doloremque consequatur voluptate autem illo officia reiciendis! Reprehenderit at quis optio voluptatum neque, labore amet tempore placeat, excepturi natus laboriosam aperiam. Explicabo incidunt repudiandae asperiores aut deserunt.</p>
    </>
}

export default Home;