


function About() {


    return <>
        <h1 style={{ color: "orange" }}>About Component</h1>
        <br />
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi debitis tempora vitae expedita, porro quibusdam, et, rerum eum aliquid ad repudiandae ut quidem eius libero impedit similique ullam quae? Nostrum, quia a culpa impedit necessitatibus doloribus ducimus in beatae iusto omnis quasi possimus. Saepe temporibus assumenda dolorem provident accusamus sequi voluptate rem dicta! Enim distinctio quo saepe at voluptate corporis sequi iure? Architecto eveniet aliquam tenetur itaque officia quos ipsam laborum! Rerum quasi nihil, expedita a harum officia, nisi cupiditate repellendus modi illo iste, eaque iusto magnam eos et quam. Hic eveniet debitis obcaecati accusamus, nulla est esse maxime perferendis assumenda facere dolorum explicabo cumque adipisci voluptatem natus distinctio totam eligendi quia earum. Hic facilis commodi laudantium, magnam nulla explicabo. Cupiditate dolor accusamus blanditiis perferendis tenetur officiis perspiciatis veniam vel voluptatum! Dicta, voluptatibus tempore doloremque, veniam neque officiis a debitis exercitationem ipsa pariatur, cupiditate officia esse. Amet deserunt eaque eius aspernatur ex perferendis cupiditate rerum doloremque maxime exercitationem quaerat modi architecto excepturi, ducimus necessitatibus ab, aperiam vitae, earum consectetur recusandae impedit atque? Provident, neque. Consequuntur nostrum odio reiciendis, ab maxime impedit excepturi ex. Quam doloribus eveniet, in veritatis cum quisquam soluta quas, consectetur distinctio, est quasi id laboriosam nesciunt temporibus reprehenderit accusamus magni dolorum ullam nostrum neque ut? Earum asperiores, quo odio molestias sapiente fuga atque esse molestiae reprehenderit assumenda laudantium corporis exercitationem, aliquid nostrum consectetur incidunt! Incidunt recusandae impedit voluptatum temporibus delectus quia neque rerum nulla amet, magnam unde ullam repellat id quaerat dolorem eum fugit similique libero, ab explicabo pariatur. Doloremque ab porro quidem placeat alias autem, odio libero maxime? Ratione molestiae adipisci harum odit non, minima nihil sit alias, omnis voluptas explicabo, nam deserunt est a veritatis laboriosam consectetur? Nulla quas quasi quod deserunt quaerat sint itaque. Ex dolorem nemo alias perspiciatis ipsam exercitationem culpa eius necessitatibus!</p>
        <br />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum ex omnis doloribus laudantium repellendus dignissimos deleniti quasi fuga, dolorum, corporis illo, sapiente id magni! Blanditiis fugiat pariatur amet sint explicabo! Illo labore molestiae, natus praesentium ab perferendis similique eligendi harum distinctio consectetur quasi eos eum iusto amet minus aliquid neque aperiam earum aliquam totam odio itaque est in? Numquam, recusandae nam sed maiores debitis qui magnam quos consequatur, facilis, laudantium ullam? Temporibus accusantium natus ullam non dolorem ratione quis reiciendis facere suscipit, quod, dolores iure dolor obcaecati omnis ex neque exercitationem ducimus voluptatum? Deleniti perspiciatis dolor quasi eius tempora corporis quos sint nam maiores? Nostrum perspiciatis voluptates adipisci animi voluptas, laudantium ut, cumque nulla, ad quae dolorem? Deleniti dolor necessitatibus est incidunt cum esse laudantium laborum quasi qui dignissimos facilis accusamus ullam excepturi laboriosam porro nihil totam quidem cumque, illum modi non vero distinctio. Quos soluta officiis dolore veritatis corporis tenetur quae, iure cupiditate ipsa quisquam pariatur magni quasi ab voluptatem dicta blanditiis cumque sequi, id eius. Voluptas tenetur nostrum molestiae officiis dolor doloribus, voluptatum architecto recusandae voluptatem quasi. Perferendis rerum nam debitis a numquam error vitae exercitationem quia commodi alias reprehenderit ipsam quasi similique tempore, quisquam laudantium? Maxime mollitia totam error beatae quasi minus fugit explicabo ipsa nihil aspernatur placeat odio modi quia doloremque voluptate quo fugiat esse rem, dolor cumque. Alias atque, illo sint expedita, nostrum maiores dolorum voluptas dolor voluptatibus, quia possimus similique iure sit! Itaque iste molestias sequi voluptate minus recusandae velit quas labore ipsa in.</p>
    </>
}

export default About;